---
name: CI CD

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  cicd:
    name: CI CD
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: build it
        run: make

      - name: does it run
        run: |
          sudo ./simple 10.20.20.20 5 >output.txt &
          sleep 1
          ifconfig >ifconfig.txt
          sudo tcpdump -e -i bridge100 >tcpdump.txt || true

      - name: Show the outputs
        run: |
          echo ifconfig.txt =================================================
          cat ifconfig.txt
          echo output.txt =================================================
          cat output.txt
          echo tcpdump.txt =================================================
          cat tcpdump.txt

      - name: save binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: simple

      - name: save output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./*.txt
